"use strict";
exports.__esModule = true;
exports["default"] = {
    multiple: '| 支持点选多个节点（节点本身） | boolean | false |',
    checkable: '| 节点前添加 Checkbox 复选框 | boolean | false |',
    defaultExpandAll: '| 默认展开所有树节点 | boolean | false |',
    defaultExpandedKeys: '| 默认展开指定的树节点 | string[] | [] |',
    expandedKeys: '| （受控）展开指定的树节点 | string[] | [] |',
    autoExpandParent: '| 是否自动展开父节点 | boolean | true |',
    defaultCheckedKeys: '| 默认选中复选框的树节点 | string[] | [] |',
    checkedKeys: '| （受控）选中复选框的树节点（注意：父子节点有关联，如果传入父节点key，则子节点自动选中；相应当子节点key都传入，父节点也自动选中。当设置`checkable`和`checkStrictly`，它是一个有`checked`和`halfChecked`属性的对象，并且父子节点的选中与否不再关联 | string[] \| {checked: string[], halfChecked: string[]} | [] |',
    checkStrictly: '| checkable状态下节点选择完全受控（父子节点选中状态不再关联）| boolean | false |',
    defaultSelectedKeys: '| 默认选中的树节点 | string[] | [] |',
    selectedKeys: '| （受控）设置选中的树节点 | string[] | - |',
    onExpand: '| 展开/收起节点时触发 | function(expandedKeys, {expanded: bool, node}) | - |',
    onCheck: '| 点击复选框触发 | function(checkedKeys, e:{checked: bool, checkedNodes, node, event}) | - |',
    onSelect: '| 点击树节点触发 | function(selectedKeys, e:{selected: bool, selectedNodes, node, event}) | - |',
    filterTreeNode: '| 按需筛选树节点（高亮），返回true | function(node) | - |',
    loadData: '| 异步加载数据 | function(node)| - |',
    onRightClick: '| 响应右键点击 | function({event, node}) | - |',
    draggable: '| 设置节点可拖拽（IE>8） | boolean | false |',
    onDragStart: '| 开始拖拽时调用 | function({event, node}) | - |',
    onDragEnter: '| dragenter 触发时调用 | function({event, node, expandedKeys}) | - |',
    onDragOver: '| dragover 触发时调用 | function({event, node}) | - |',
    onDragLeave: '| dragleave 触发时调用 | function({event, node}) | - |',
    onDragEnd: '| dragend 触发时调用 | function({event, node}) | - |',
    onDrop: '| drop 触发时调用 | function({event, node, dragNode, dragNodesKeys}) | - |',
    showLine: '| 是否展示连接线 | boolean | false |',
    showIcon: '| 是否展示 TreeNode title 前的图标，没有默认样式，如设置为 true，需要自行定义图标相关样式 | boolean | false |'
};
